name: PR Validation
description: Does PR validation on github pull requests 
author: https://github.com/devdil
requirements:
  - docker
configuration:
  properties:
    pr-title:
      type: string
  additionalProperties: false
  required: []
