#!/usr/bin/python 
import os

print("Hello from the Buildkite plugin!")

# Example of using an environment variable
build_number = os.environ.get('BUILDKITE_BUILD_NUMBER')
print(f"Build number: {build_number}")
