#!/bin/bash
set -euo pipefail
echo "----------------------------"
echo $BASH_SOURCE
echo "----------------------------"
echo $0
echo "----------------------------"

docker run -it --rm --name validation-test diljitpr/pr-validation-buildkite-scripts:latest
